# Generated by Django 2.2.10 on 2020-09-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер дома')),
                ('house_building', models.CharField(blank=True, max_length=30, null=True, verbose_name='Корпус дома')),
                ('apartment', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер квартиры')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адрес',
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='full_address',
        ),
        migrations.AddField(
            model_name='company',
            name='apartment',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='company',
            name='house',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='company',
            name='house_building',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Корпус дома'),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
