# Generated by Django 2.2.10 on 2020-07-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф на день', 'verbose_name_plural': 'Тариф на день'},
        ),
    ]
