# Generated by Django 2.2.10 on 2020-09-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201001_0239'),
        ('users', '0002_auto_20200723_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tariff',
        ),
        migrations.AddField(
            model_name='tariff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_company', to='company.Company', verbose_name='Компания'),
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('address_for_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_delivery_address', to='company.Address', verbose_name='Адрес доставки')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups_company', to='company.Company', verbose_name='Компания')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_group', to='users.Tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Группы пользователей',
                'verbose_name_plural': 'Группы пользователей',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_group', to='users.CustomGroup', verbose_name='Группа'),
        ),
    ]
