# Generated by Django 2.2.10 on 2020-12-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201001_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='address_for_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_delivery_address', to='company.DeliveryAddress', verbose_name='Адрес доставки'),
        ),
    ]
