# Generated by Django 2.2.10 on 2020-09-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200723_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id'], 'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('dish', 'Блюдо'), ('avatar', 'Аватар')], max_length=6, verbose_name='Тип фотографии'),
        ),
    ]
