# Generated by Django 2.2.10 on 2020-11-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_auto_20201001_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'В обработке'), (1, 'Принят'), (2, 'Отменен'), (3, 'Подтвержден')], default=3, verbose_name='Статус'),
        ),
    ]
